services:
  kong:
    image: kong:3.6
    container_name: kong-gateway
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - kong-net
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      - KC_USER=admin
      - KC_PASSWORD=admin
      - KC_REALM=pfe-realm
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    networks:
      - kong-net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kong-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - QUARKUS_HTTP_PORT=8081
      - QUARKUS_OIDC_AUTH_SERVER_URL=http://keycloak:8080/realms/pfe-realm
      - QUARKUS_OIDC_CLIENT_ID=quarkus-be
      - QUARKUS_OIDC_CREDENTIALS_SECRET=lKSVEtQNeq3BTagQkiHHJLM69bQPCuWW
      - KEYCLOAK_SERVERURL=http://keycloak:8080
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=omarkdhai@gmail.com
    depends_on:
      - keycloak
    networks:
      - default
      - kong-net

  

  notif-service:
    build:
      context: ./notif-service
    container_name: notif-service
    ports:
      - "8083:8083"
    environment:
      - QUARKUS_HTTP_PORT=8083
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017
      - QUARKUS_MONGODB_DATABASE=notif-service
    depends_on:
      - mongo

  support-service:
    build:
      context: ./support-service
    container_name: support-service
    ports:
      - "8084:8084"
    environment:
      - QUARKUS_HTTP_PORT=8084
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017
      - QUARKUS_MONGODB_DATABASE=support-service
    depends_on:
      - mongo

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8085:8085"
    environment:
      - QUARKUS_HTTP_PORT=8085
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017
      - QUARKUS_MONGODB_DATABASE=payment-service
    depends_on:
      - mongo  
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge

volumes:
  mongo_data:
  postgres_data: