services:
  kong:
    image: kong:3.6
    container_name: kong-gateway
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - kong-net
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      - KC_USER=admin
      - KC_PASSWORD=admin
      - KC_REALM=pfe-realm
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    networks:
      - kong-net

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
    ports:
      - "55655:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kong-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

networks:
  kong-net:
    driver: bridge

volumes:
  mongo_data:
  postgres_data: