version: "3.8"

services:
  gateway:
    build: .
    container_name: krakend-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
      - notif-service
    networks:
      - backend

  auth-service:
    image: my-auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    networks:
      - backend

  product-service:
    image: my-product-service
    container_name: product-service
    ports:
      - "8082:8082"
    networks:
      - backend

  notif-service:
    image: my-notif-service
    container_name: notif-service
    ports:
      - "8083:8083"
    networks:
      - backend

networks:
  backend:
    driver: bridge
